# Generated by Django 4.1 on 2023-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_alter_coordinate_lat_alter_coordinate_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinate",
            name="lat",
            field=models.DecimalField(decimal_places=30, max_digits=35),
        ),
        migrations.AlterField(
            model_name="coordinate",
            name="lng",
            field=models.DecimalField(decimal_places=30, max_digits=35),
        ),
    ]
