runtime: python39 

instance_class: "F2"

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  APPENGINE_URL: https://safewalk-testing-ae.uc.r.appspot.com