# Generated by Django 4.1 on 2023-08-26 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="email",
            new_name="contact_email",
        ),
    ]
